{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_conv_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "filters_layer_1", "default": 32, "conditions": [], "values": [32, 64, 128], "ordered": true}}, {"class_name": "Int", "config": {"name": "num_dense_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_dense_1", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "filters_layer_2", "default": 32, "conditions": [], "values": [32, 64, 128], "ordered": true}}, {"class_name": "Choice", "config": {"name": "filters_layer_3", "default": 32, "conditions": [], "values": [32, 64, 128], "ordered": true}}, {"class_name": "Int", "config": {"name": "units_dense_2", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}], "values": {"num_conv_layers": 3, "filters_layer_1": 32, "num_dense_layers": 2, "units_dense_1": 128, "learning_rate": 0.001, "filters_layer_2": 32, "filters_layer_3": 32, "units_dense_2": 32}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/fp/homes01/u01/ec-gerald/.conda/envs/MLEINVIRONMENT/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/fp/homes01/u01/ec-gerald/.conda/envs/MLEINVIRONMENT/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/fp/homes01/u01/ec-gerald/.conda/envs/MLEINVIRONMENT/lib/python3.11/site-packages/keras_tuner/engine/tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/fp/homes01/u01/ec-gerald/.conda/envs/MLEINVIRONMENT/lib/python3.11/site-packages/keras_tuner/engine/tuner.py\", line 214, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/fp/homes01/u01/ec-gerald/.conda/envs/MLEINVIRONMENT/lib/python3.11/site-packages/keras_tuner/engine/hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/fp/homes01/u01/ec-gerald/.conda/envs/MLEINVIRONMENT/lib/python3.11/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/fp/homes01/u01/ec-gerald/.conda/envs/MLEINVIRONMENT/lib/python3.11/site-packages/tensorflow/python/trackable/data_structures.py\", line 823, in __getattribute__\n    return super().__getattribute__(name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: this __dict__ descriptor does not support '_DictWrapper' objects\n"}